sudo: required
services:
  - docker

before_install:
  - docker build -t bilmakovchik/react-docker-example -f Dockerfile.dev .

script:
  - docker run bilmakovchik/react-docker-example npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-188419695974"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

